//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Constant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatePlayersMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatePlayersMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.Constant.CreatePlayersMessages", typeof(CreatePlayersMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you want choose word from 
        ///1.DataBase; 
        ///2. Write yours words;
        ///1 or 2?.
        /// </summary>
        internal static string ChooseWordsFromDB {
            get {
                return ResourceManager.GetString("ChooseWordsFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0}.
        /// </summary>
        internal static string ForDisplayCommandName {
            get {
                return ResourceManager.GetString("ForDisplayCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        internal static string ForDisplayNameOfPlayers {
            get {
                return ResourceManager.GetString("ForDisplayNameOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Command {0} Pleas write the name of players. When you will finish pleas write &quot;end&quot; and press enter.
        /// </summary>
        internal static string InstructionForFillPlayersName {
            get {
                return ResourceManager.GetString("InstructionForFillPlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, pleas put down your word, after, press enter and write your next word..
        /// </summary>
        internal static string InstructionForFillWords {
            get {
                return ResourceManager.GetString("InstructionForFillWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quontity of words =.
        /// </summary>
        internal static string QuonityOfWords {
            get {
                return ResourceManager.GetString("QuonityOfWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string SingOfEndOfTypingInCycle {
            get {
                return ResourceManager.GetString("SingOfEndOfTypingInCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Write number of commands.
        /// </summary>
        internal static string WriteNumOfCommand {
            get {
                return ResourceManager.GetString("WriteNumOfCommand", resourceCulture);
            }
        }
    }
}
